import 'babel-polyfill'
// import './class/let&const'
// import './class/destructuring-assignment'
// import './class/regular'
// import './class/string'
// import './class/array'
// import './class/function'
// import './class/symbol'
// import './class/set&map'
// import './class/proxy&reflect'
// import './class/class'
// import './class/promise'
// import './class/iterator'
// import './class/generator'
import './class/decorator'


